# Generated by Django 2.2.16 on 2022-09-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220911_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Здесь можно загрузить картинку, объёмом не более 5Мб', upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
